targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-pc-windows-gnu" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/rustsec/advisory-db"
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []


[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "ISC",
    "OpenSSL",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "CC0-1.0",
]
deny = []
copyleft = "allow"
default = "deny"
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [ { path = "LICENSE", hash = 0xbd0eed23 } ]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
