version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    expose:
      - "8080"
    labels:
      - "net.gegy1000.vertex=server"
    volumes:
      - ./server/docker/logs:/.local/share/vertex_server/logs
    environment:
      - VERTEX_SERVER_KEY_PASS=${VERTEX_SERVER_KEY_PASS}
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - vertex_postgres_db:/var/lib/db
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vertex

volumes:
  vertex_postgres_db:
