version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    expose:
      - "8080"
    labels:
      - "net.gegy1000.vertex=server"
    environment:
      - XDG_CONFIG_HOME="/vertex/server/config"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - data-volume:/var/lib/db
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vertex

volumes:
  data-volume:
