[package]
name = "vertex_client_backend"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "^0.22"
uuid = { version = "^0.7", features = ["serde", "v4"] }
serde = "^1"
serde_cbor = "^0.9"
vertex_common = { path = "../../common/" }
url = "^1.7"
futures = "^0.1"
tokio = { version = "^0.1" }
crossbeam = "^0.7"
actix = { version = "^0.8" }
