[package]
name = "vertex_client"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>", "gegy1000 <gegy1000@gmail.com>"]
edition = "2018"

[dependencies]
vertex = { path = "../../common/" }

futures = "0.3"

async-trait = "0.1"
