[package]
name = "vertex_client_gtk"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>", "gegy1000 <gegy1000@gmail.com>"]
edition = "2018"

[dependencies]
gio = "0.8"
glib = "0.9"
gdk = "0.12"
gtk = { version = "0.8", features = ["v3_20"] }
clap = "2.33"

url = "2.1"
uuid = { version = "^0.8", features = ["serde", "v4"] }
keyring = "^0.7"

serde = "^1"
serde_derive = "^1"
serde_json = "^1"
serde_cbor = "0.11"

futures = "0.3"
tokio = { version = "0.2.9", features = ["full"] }

tungstenite = "0.9"
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite.git", features = ["tls"] }

native-tls = "0.2"
tokio-tls = "0.3"

async-trait = "0.1"

vertex_client = { path = "../backend/" }
vertex = { path = "../../common" }
