[package]
name = "vertex_server"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
actix = "^0.9"
actix-web = { version = "^2", features = ["openssl"] }
actix-web-actors = "^2"
actix-files = "^0.2"
actix-service = "^1"
serde = "^1"
serde_cbor = "^0.10"
websocket = "^0.23"
url = "^2"
futures = "^0.3"
l337 = { git = "https://github.com/OneSignal/L3-37", rev = "a970fe669787c4caf8ae699870b97ed1d7616f00" }
l337-postgres = { git = "https://github.com/OneSignal/L3-37", rev = "a970fe669787c4caf8ae699870b97ed1d7616f00" }
tokio = { version = "^0.2", features = ["rt-threaded", "blocking"] }
tokio-postgres = { version = "^0.5", features = ["with-uuid-0_8", "with-chrono-0_4"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
rust-argon2 = "^0.5"
rand = "^0.7"
lazy_static = "^1"
bitflags = "^1"
base64 = "^0.10"
directories = "^2"
toml = "^0.5"
unicode-normalization = "^0.1"
openssl = "^0.10"
log = "^0.4"
fern = "^0.5"
dashmap = "^3"
vertex_common = { path = "../common/", features = ["enable-actix"] }
