[package]
name = "vertex_server"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
actix = "^0.8"
actix-web = { version = "^1", features = ["ssl"] }
actix-web-actors = "^1"
actix-files = "^0.1"
actix-service = "^0.4"
serde = "^1"
serde_cbor = "^0.10"
dashmap = "^1"
websocket = "^0.23"
url = "^2"
futures = "^0.1"
l337 = { git = "https://github.com/OneSignal/L3-37", rev = "369454b7312ef68a60f5d2df30ad2544fec50359" }
l337-postgres = { git = "https://github.com/OneSignal/L3-37", rev = "369454b7312ef68a60f5d2df30ad2544fec50359" }
tokio = "^0.1"
tokio-postgres = { version = "0.4.0-rc.2", features = ["with-uuid-0_7", "with-chrono-0_4"] }
uuid = { version = "0.7", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
tokio-threadpool = "^0.1"
rust-argon2 = "^0.5"
rand = "^0.7"
lazy_static = "^1"
bitflags = "^1"
base64 = "^0.10"
directories = "^2"
toml = "^0.5"
unicode-normalization = "^0.1"
openssl = "^0.10"
vertex_common = { path = "../common/", features = ["enable-actix"] }
