[package]
name = "vertex_server"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
actix = "^0.8"
actix-web = "^1"
actix-web-actors = "^1"
serde = "^1"
serde_cbor = "^0.9"
ccl = "^3"
websocket = "^0.22"
url = "^1.7"
futures = "^0.1"
uuid = { version = "^0.7", features = ["serde", "v4"] }
l337 = { git = "https://github.com/OneSignal/L3-37", rev = "369454b7312ef68a60f5d2df30ad2544fec50359" }
l337-postgres = { git = "https://github.com/OneSignal/L3-37", rev = "369454b7312ef68a60f5d2df30ad2544fec50359" }
tokio = "^0.1"
tokio-postgres = { version = "0.4.0-rc.2", features = ["with-uuid-0_7"] }
tokio-threadpool = "^0.1"
rust-argon2 = "^0.4"
rand = "0.7.0-pre.1"
vertex_common = { path = "../common/", features = ["enable-actix"] }
lazy_static = "^1"
