[package]
name = "vertex"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_derive = "^1"
serde_cbor = "^0.9"
uuid = { version = "0.8", features = ["serde", "v4"] }
bytes = { version = "^0.5", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bitflags = "^1"
