[package]
name = "vertex_common"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_derive = "^1"
serde_cbor = "^0.9"
actix = { version = "^0.8", optional = true }
uuid = { version = "^0.7", features = ["serde", "v4"] }
bytes = { version = "^0.4.12", features = ["serde"] }

[features]
enable-actix = ["actix"]
